### ISSUE TITLE
If GIT_DIR isn't set, then this could accidentally clear out _everything_ (rm -rf)

### ISSUE THREAD

**Issue by dci-aloughran** [gchamon/terraform-aws-bucket-antivirus#5]
https://github.com/gchamon/terraform-aws-bucket-antivirus/blob/a767b340b72c65d12061e64f6cf3b7b35a9d06ed/scripts/build-antivirus-from-source.sh#L8

**Comment by gchamon** [comment]
GIT_DIR is always set here: https://github.com/gchamon/terraform-aws-bucket-antivirus/blob/a767b340b72c65d12061e64f6cf3b7b35a9d06ed/scripts/build-antivirus-from-source.sh#L4

Even so you must pass `--no-preserve-root` to clear out everything.

However, just to be rock solid, I could fix this by passing the trailing slash `/` to `$GIT_DIR`, that would solve the potential issue

**Comment by gchamon** [comment]
#6 should fix it

**Comment by dci-aloughran** [comment]
Yep, good job 👍
