### ISSUE TITLE
Making the lambda.zip artifact optional.

### ISSUE THREAD

**Issue by dci-aloughran** [gchamon/terraform-aws-bucket-antivirus#8]
To "workaround" my problems with the local-exec.

Could we develop the pattern for the lambda.zip file to be present in a folder, and if not present then generated.

That way those of us that wish to build lambda.zip outside the terraform flow could reference the zipfile?

**Comment by gchamon** [comment]
working on it

there seems to be a problem with recent s3 bucket permissions I am fixing right now. Will get back as soon as I implement it

**Comment by gchamon** [comment]
addressed in #9 

could you take a look?

**Comment by gchamon** [comment]
ok, so bucket-antivirus-function is not working in the current state. Update function has wrong python imports and bad permissions, and scanner function doesn't even import the antivirus definitions database correctly

I recommend using downgrading to upsidetravel/bucket-antivirus-function@90b1061

**Comment by gchamon** [comment]
Since I didn't hear from you again, I will close this issue, but if problem persists feel free to open a new one =D
